### delete a resource (change id as needed)
DELETE http://localhost:3001/api/persons/3

### add a resource (change values as needed)
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "New",
    "number": "123-4567890"
}


### GET all
GET http://localhost:3001/api/persons

### GET info
GET http://localhost:3001/info